language: php

php:
  - 5.5
  - 5.6
  - 7.0

services:
  - postgresql

addons:
  postgresql: "9.5"

sudo: required
dist: precise

before_script:
  - 'composer install --dev --prefer-source'
  - psql -c 'create database mindplay_sql_test;' -U postgres

script: php test/test.php

after_script:
  - if [ $(phpenv version-name) = "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $(phpenv version-name) = "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover test/build/clover.xml; fi
